name: test
on: push
jobs:
  test:
    runs-on: [self-hosted, ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: All test
        run: bash -xv ./test.bash
